INSERT INTO MEMBER(ID, NAME, OWNED_AMOUNT, JOIN_YN, CREATED_AT, MODIFIED_AT)
VALUES(1, 'TEST', 10000, 'Y', NOW(), NOW());

INSERT INTO MEMBER_PAYMENT_LIMIT(ID, MEMBER_ID, PAYMENT_LIMIT_TYPE, LIMIT_AMOUNT, CREATED_AT, MODIFIED_AT)
VALUES(1, 1, 'ONE_TIME', 1000, NOW(), NOW());

INSERT INTO MEMBER_PAYMENT_LIMIT(ID, MEMBER_ID, PAYMENT_LIMIT_TYPE, LIMIT_AMOUNT, CREATED_AT, MODIFIED_AT)
VALUES(2, 1, 'ONE_DAY', 5000, NOW(), NOW());

INSERT INTO MEMBER_PAYMENT_LIMIT(ID, MEMBER_ID, PAYMENT_LIMIT_TYPE, LIMIT_AMOUNT, CREATED_AT, MODIFIED_AT)
VALUES(3, 1, 'THIRTY_DAY', 9000, NOW(), NOW());


